### PR TITLE
Remove spray-json dependency

### PR DESCRIPTION
**Pull request by Tvaroh**
Looks like no need to depend on `spray-json`.

### CODE REVIEW

**Comment by pjfanning** [comment]
I published a 0.8.1-SNAPSHOT jar to maven

**Comment by Tvaroh** [comment]
@pjfanning thanks. When to expect `0.8.1` final?

**Comment by pjfanning** [comment]
just released 0.8.1

**Comment by Tvaroh** [comment]
Great, thank you.

**Pull request merged**
